"""adds constraints and validations to books table

Revision ID: a6b9565c30b8
Revises: b37032f7dab3
Create Date: 2024-10-15 16:05:53.225368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b9565c30b8'
down_revision = 'b37032f7dab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('condition',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('new', 'used', name='book_condition'),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('rent', 'sale', name='book_status'),  # Updated to ENUM
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('rent', 'sale', name='book_status'),  # Rollback to ENUM
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('condition',
               existing_type=sa.Enum('new', 'used', name='book_condition'),
               type_=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
